AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pdf-html

Globals:
  Function:
    Timeout: 300

Resources:
  PDFGeneratorFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.pdfGenerator
      MemorySize: 2048
      Timeout: 300
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        PDFGenerator:
          Type: Api
          Properties:
            Path: /pdf
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
