AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pdf-dynamic

Globals:
  Function:
    Timeout: 300

Resources:
  PDFFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/
      Handler: app.pdfCreate
      MemorySize: 1024
      Timeout: 300
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        PDFGenerator:
          Type: Api 
          Properties:
            Path: /pdf
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  PDFGeneratorApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PDFGeneratorFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PDFGeneratorFunction.Arn
  PDFGeneratorFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PDFGeneratorFunctionRole.Arn
